# Ways to Create a numpy array

In [ ]:
import numpy as np

a = np.array([1,2,3])

print(type(a))

<class 'numpy.ndarray'>


In [ ]:
# dtype is used to define the datatype

b = np.array([1,2,3],dtype=complex)
print(b)

[1.+0.j 2.+0.j 3.+0.j]


In [ ]:
# range with slices

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# range with reshape

np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

- np.ones , np.zeros , np.random are use to initialize the array

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.random.random((3,3))

array([[0.62825956, 0.20040522, 0.20022464],
       [0.69090798, 0.55832694, 0.62820817],
       [0.71533467, 0.70439842, 0.45765146]])

In [ ]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# NP array attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim
a3.ndim

3

In [ ]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize
a3.itemsize

8

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


# Changing datatype

In [23]:
a3 = np.arange(8).reshape(2,2,2)
a3
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operation

In [24]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [26]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [27]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Functions

In [28]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[75.,  8., 32.],
       [18., 12., 89.],
       [73., 22.,  4.]])

In [32]:
# max/min/sum/prod
# 0 -> col and 1 -> row
# axis is used for row wise or column wise calculation
np.prod(a1,axis=0)

array([98550.,  2112., 11392.])

In [30]:
# mean/median/std/var
np.var(a1,axis=1)

array([ 768.22222222, 1222.88888889,  854.        ])

In [33]:
# trigonomoetric functions
np.sin(a1)

array([[-0.38778164,  0.98935825,  0.55142668],
       [-0.75098725, -0.53657292,  0.86006941],
       [-0.67677196, -0.00885131, -0.7568025 ]])

In [34]:
# dot product
# column of first must be equal to row of second
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [35]:
# log and exponents
np.exp(a1)

array([[3.73324200e+32, 2.98095799e+03, 7.89629602e+13],
       [6.56599691e+07, 1.62754791e+05, 4.48961282e+38],
       [5.05239363e+31, 3.58491285e+09, 5.45981500e+01]])

In [36]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[ 83., 100.,  98.],
       [ 89.,  37.,  88.]])

# Indexing and Slicing

In [37]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [39]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [40]:
a3[::2,0,::2]

array([[0]])

# Iteration

In [41]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [42]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [43]:
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [44]:
# converts multi-D array into 1D first

for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7


# Reshaping

In [45]:
# Transpose
# Reshape has been coverd above
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [46]:
# ravel
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

# Stacking

In [47]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
# Horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [49]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Spliting

In [50]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [52]:
np.vsplit(a4,1)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])]